extends:
  - "airbnb"

env:
  browser: true # Added for eslint to allow using DOM objects
  jest/globals: true


rules:
  import/extensions:
    - error
    - js: ignorePackages # Enabling the use of `.js` in import statements
  
overrides:
  - files: ["source/sw.js"]
    rules:
      no-restricted-globals: [0]

plugins:
- jest